Issue 92 read account
UnBArqDsw/2020.1_G2_TCLDL_Paper_Service pull request #17
Opened 2020-10-22 18:29 UTC by gdeusdara

2020-10-23 19:17 UTC, gabrielfilipe7unb commented
Issue #92 - MonoRepo

2020-10-26 18:01 UTC, ygortgaleno requested changes

2020-10-26 18:01 UTC, ygortgaleno commented on src/data/interactors/UpdateUserAdapterDb.spec.ts
> +class UpdateUserRepositoryStub implements FindUserRepository {
Update repository deve implementar um update repository que vai ser um repository somente responsavel por atualizar

2020-10-26 18:01 UTC, ygortgaleno commented on src/data/repositories/ReadUserRepository.ts
> +import { User } from '@domain/entities/User';
O read user repository é o mesmo find user repository, esse arquivo é desnecessário

2020-10-26 18:01 UTC, ygortgaleno commented on src/data/repositories/ReadUserRepository.ts
> +  execute: (attribute: findUserAttribute) => Promise<User | undefined>
Ao invés de usar o findUserAttribute, substituir pelo Partial, que vai ser substituido tbm pelo DTOs na proxima entrega.

2020-10-26 18:01 UTC, ygortgaleno commented on src/data/repositories/UpdateUserRepository.ts
> +export interface UpdateUserRepository {
Mesma coisa do find user

2020-10-26 18:01 UTC, ygortgaleno commented on src/domain/interactors/ReadUser.ts
> +export interface ReadUser {
Arquivo desnecessário, é o mesmo do find user.

2020-10-26 18:01 UTC, ygortgaleno commented on src/infra/db/typeorm/repositories/FindUserRepositoryAdapter.ts
> +    console.log(parameter)
remover esse console

2020-10-26 18:01 UTC, ygortgaleno commented on src/infra/db/typeorm/repositories/ReadUserRepositoryAdapter.ts
> +export class ReadUserRepositoryAdapter implements ReadUserRepository {
classe desnecessária

2020-10-26 18:01 UTC, ygortgaleno commented on src/infra/request_validators/ReadUserRequestValidator.ts
> +export class ReadUserRequestValidator implements RequestValidator {
read user não precisa de um body validator, rotas get não recebe o body no request

2020-10-26 18:01 UTC, ygortgaleno commented on src/infra/request_validators/UpdateUserRequestValidator.ts
> +      id: joi.string(),
id é imutável, ele não pode estar em um body validator

2020-10-26 18:01 UTC, ygortgaleno commented on src/presentation/controllers/ReadUserController.spec.ts
> +import { User } from '@domain/entities/User';
esse teste na verdade ta testando o update controller

2020-10-26 18:01 UTC, ygortgaleno commented on src/presentation/controllers/UpdateUserController.ts
> +      return successCreate(user);
success create é somente para criação, atualização continua o status 200 de success request(204 tbm é aceito, mas já estamos usando no remove user)

2020-10-26 18:01 UTC, ygortgaleno commented on src/presentation/middlewares/ReadUserValidatorMiddleware.ts
> +import { badRequest, successRequest } from '@presentation/helpers/HttpHelper';
Read user não tem validação de body

2020-10-26 18:01 UTC, ygortgaleno commented on src/server/config/routes.ts
> +    console.log(file)
remover consoles

2020-10-26 18:01 UTC, ygortgaleno commented on src/server/routes/UpdateUserRoute.spec.ts
> +      test('should return 204', async () => {
corrigir descrição de testes

2020-10-26 23:03 UTC, gdeusdara commented on src/presentation/middlewares/ReadUserValidatorMiddleware.ts
> +import { badRequest, successRequest } from '@presentation/helpers/HttpHelper';
Precisa?

2020-10-27 00:22 UTC, gdeusdara commented on src/data/repositories/ReadUserRepository.ts
> +  execute: (attribute: findUserAttribute) => Promise<User | undefined>
Isso aqui foi tu que fez kkk

2020-11-20 23:30 UTC, ygortgaleno approved these changes

2020-11-20 23:30 UTC, merged